version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: projet_pfe
      PGDATA: /var/lib/postgresql/data/some_name/
    volumes:
    - /var/lib/docker/volumes:/var/lib/postgresql/data

  my_app:
    image: wejdenemenaa/projet_pfe
    restart: always
    ports:
      - 80:80
    depends_on:
      - db

networks:
    default:
        driver: bridge
